version: 0.2

phases: 
  install:
    runtime-versions:
      python: 3.12
    commands:
      - npm install --silent --np-progress -g serverless
  build:
    commands:
      - echo "Starting serverless deployment"
      - serverless login
      - serverless deploy --stage $ENVIRONMENT --region $REGION --conceal --verbose
      - echo "Finish deployment"